# Generated by Django 5.2.5 on 2025-09-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_phoneotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='lessonasset',
            name='storage_key',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
