# Generated by Django 5.2.5 on 2025-09-11 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_lesson_is_preview_enrollment'),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='orgs.org'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='orgs.org'),
        ),
        migrations.AddField(
            model_name='module',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='orgs.org'),
        ),
        migrations.AlterField(
            model_name='lessonasset',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.org'),
        ),
    ]
