# Generated by Django 5.2.5 on 2025-09-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_course_code'),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lessonasset',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonasset',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='lessonasset',
            index=models.Index(fields=['lesson', 'published', 'is_preview'], name='asset_vis_idx'),
        ),
    ]
