# Generated by Django 5.2.5 on 2025-09-25 17:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_course_description_lessonasset_is_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
