# Generated by Django 5.2.5 on 2025-09-04 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('KG', 'KG'), ('UNI', 'University'), ('CERT', 'Certification')], default='KG', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.org')),
            ],
            options={
                'unique_together': {('org', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('kind', models.CharField(blank=True, max_length=30)),
                ('duration_months', models.PositiveIntegerField(default=0)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='orgs.catalog')),
            ],
            options={
                'unique_together': {('catalog', 'code')},
            },
        ),
        migrations.CreateModel(
            name='OrgMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ORG_ADMIN', 'ORG_ADMIN'), ('TEACHER', 'TEACHER'), ('STUDENT', 'STUDENT'), ('PARENT', 'PARENT'), ('MODERATOR', 'MODERATOR')], max_length=20)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.org')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('org', 'user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='orgs.program')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('program', 'label')},
            },
        ),
    ]
